1.

In [3]:
import numpy as np
a=np.arange(2,50,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


2.

In [11]:
lst1 = list(map(int,input().strip().split()))[:5] 
lst2 = list(map(int,input().strip().split()))[:5] 
arr1 = np.array(lst1)
arr2 = np.array(lst2)
print(lst1)
print(lst2)
print(arr1)
print(arr2)
arr = np.concatenate([arr1,arr2])
print(arr)
print(np.sort(arr))

1 23 6 8 4
4 6 9 8 78
[1, 23, 6, 8, 4]
[4, 6, 9, 8, 78]
[ 1 23  6  8  4]
[ 4  6  9  8 78]
[ 1 23  6  8  4  4  6  9  8 78]
[ 1  4  4  6  6  8  8  9 23 78]


3.

In [12]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6


4.

In [19]:
x = np.array([5, 6, 7, 8, 9, 10])
print(x)
print(x.ndim)
print(x.shape)

#using np.newaxis
y=np.array(x)[np.newaxis,:]
print(y)
print(y.ndim)
print(y.shape)

#using np.expand_dims
z=np.expand_dims(x, axis=0)
print(z)
print(z.ndim)
print(z.shape)

#using np.reshape
w=np.reshape(x,(2, 3))
print(w)
print(w.ndim)
print(w.shape)

[ 5  6  7  8  9 10]
1
(6,)
[[ 5  6  7  8  9 10]]
2
(1, 6)
[[ 5  6  7  8  9 10]]
2
(1, 6)
[[ 5  6  7]
 [ 8  9 10]]
2
(2, 3)


5.

In [22]:
arr1=np.arange(9)
arr1=np.reshape(arr1,(3,3))
print(arr1)
arr2=np.arange(10,19).reshape(3,3)
print(arr2)
v_arr=np.vstack((arr1,arr2))
print(v_arr)
h_arr=np.hstack((arr1,arr2))
print(h_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


6.

In [27]:
array=np.array([0, 1, 3, 4, 1, 2, 3, 0, 1, 4, 3, 2, 0, 2, 1])
(unique, count) = np.unique(array, return_counts=True)
frequencies = np.asarray((unique, count)).T #.T is used to take the transpose of matrix
print(frequencies)

[[0 3]
 [1 4]
 [2 3]
 [3 3]
 [4 2]]
